### ISSUE TITLE
Allow custom cell instead of UITableViewCellStyle

### ISSUE THREAD

**Issue by wousser** [moritzsternemann/SwipyCell#11]
Is it possible to use a custom cell style with SwipyCell?

**Comment by moritzsternemann** [comment]
Sorry for taking so long to respond.

If I understand your problem correctly this should work totally fine.
You can just omit the arguments in the `SwipyCell` constructor and build your own cell from scratch.
However if you are using Storyboards/XIBs you can just set the `UITableViewCellStyle` to *Custom* and use the following code in your `tableView(_, cellForRowAt indexPath: IndexPath)` method:
```swift
tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as! SwipyCell
``` 

This is the preferred way to initialize a `UITableViewCell`anyways.
I've updated the included [Example](https://github.com/moritzsternemann/SwipyCell/tree/master/Example) and the [README](https://github.com/moritzsternemann/SwipyCell/tree/master/README.md) accordingly.

Fixed in [v2.0.4](https://github.com/moritzsternemann/SwipyCell/releases/tag/2.0.4) (#12)
